language: python

services:
  - memcached

python:
  - 2.7
  # - 3.3

env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6

# matrix:
#   exclude:
#     - python: 3.3
#       env: DJANGO=1.4.10
#     - python: 3.3
#       env: DJANGO=1.5.5

branches:
  only:
    - master
    - develop

install:
  - "pip install Django==$DJANGO"
  - "pip install -e ."

script:
    python runtests.py
